[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
syntax enable
colorscheme tender
if (has("termguicolors"))
 set termguicolors
endif
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_theme = 'tender'
let g:airline_enable_branch = 1 
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'neoclide/coc-git'


[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'szw/vim-maximizer'



[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'
[[plugins]]
repo = 'junegunn/fzf.vim'
